services:
  api:
    volumes:
      - /opt/mailtesterbox-web:/app/public:ro
    networks:
      - default
      - edge
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=edge"

      - "traefik.http.routers.mailtester.rule=Host(`mailtesterbox.com`) || Host(`www.mailtesterbox.com`)"
      - "traefik.http.routers.mailtester.entrypoints=websecure"
      - "traefik.http.routers.mailtester.tls=true"
      - "traefik.http.routers.mailtester.tls.certresolver=le"

      - "traefik.http.middlewares.mailtester-wwwstrip.redirectregex.regex=^https?://www\\.mailtesterbox\\.com/(.*)"
      - "traefik.http.middlewares.mailtester-wwwstrip.redirectregex.replacement=https://mailtesterbox.com/$${1}"
      - "traefik.http.middlewares.mailtester-wwwstrip.redirectregex.permanent=true"

      - "traefik.http.middlewares.mailtester-headers.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.mailtester-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.mailtester-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.mailtester-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.mailtester-headers.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.mailtester-headers.headers.referrerPolicy=strict-origin-when-cross-origin"

      - "traefik.http.middlewares.mailtester-headers.headers.contentSecurityPolicy=default-src 'self'; img-src 'self' data:; object-src 'none'; base-uri 'none'; form-action 'self'"

      - "traefik.http.middlewares.mailtester-compress.compress=true"
      - "traefik.http.middlewares.mailtester-compress.compress.excludedContentTypes=font/woff2"

      - "traefik.http.routers.mailtester.middlewares=mailtester-wwwstrip,mailtester-headers,mailtester-compress"
      - "traefik.http.services.mailtester.loadbalancer.server.port=8000"

networks:
  edge:
    external: true
